### ISSUE TITLE
Far Lands wont spawn

### ISSUE THREAD

**Issue by TyranntX** [OpenCubicChunks/CubicWorldGen#14] opened 2019-02-17 05:14 UTC
I have the option for the Farlands to generate, but they wont. I also have Cubic Chunks so I'm not sure what it is that is casing this issue

**Comment by Niko-sk2x** [comment] 2019-02-17 14:14
Did you use default generator settings otherwise, and use CustomCubic world type?
Did you teleport to the coordinates where farlands normally generate?

This option is really only there because some people requested it, and it was simple to add. There really isn't anything that can break, and I was able to get them to generate just a few days ago. So closing for now until it's actually confirmed.

**Closed as completed by Niko-sk2x** 2019-02-17 14:14 UTC
