### ISSUE TITLE
Certain CustomCubic options can only be modified through directly editing preset text

### ISSUE THREAD

**Issue by muzikbike** [OpenCubicChunks/CubicWorldGen#46] opened 2019-08-18 22:01 UTC
![2019-08-18_23 01 04](https://user-images.githubusercontent.com/52297970/63230930-21901e80-c20c-11e9-95f7-ba3586652615.png)

These should preferably have dedicated buttons and sliders implemented.

**Comment by Niko-sk2x** [comment] 2019-08-19 13:38
Duplicate of https://github.com/OpenCubicChunks/CubicWorldGen/issues/28.

**Closed as completed by Niko-sk2x** 2019-08-19 13:38 UTC
Labels: duplicate

**Comment by Niko-sk2x** [comment] 2019-08-19 13:39
CubeAreas config will never have any GUI. The target is to replace most of it's functionality with something more user friendly.
